# Modeling 
- Alcohol vs Sulphates
- Free sulfur dioxide vs Total sulfur dioxide
- Volatile acidity vs density
- Citric Acid vs pH

In [1]:
# normal imports
import final_wrangle as wr
import final_explore as ex

In [2]:
# imports for kmeans:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans

from pydataset import data


In [3]:
# import the wine datafram: 
df = wr.wine_df()
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality wine_color  
0      9.4        5        red  
1      9.8        5        red  
2      9.8        5        red  
3      9.8        6        red  
4      9.4        5        red

In [4]:
# clean the data
clean_df = wr.clean_wine(wr.wine_df())

In [5]:
# remove the outliers
clean_df = wr.remove_outliers(clean_df, 3)

In [6]:
# split the data into train validate and test:
target = 'quality'
train, validate, test = wr.split_data(clean_df, target)

In [7]:
# drop column: 
del clean_df['wine_color']
del train['wine_color']
del validate['wine_color']
del test['wine_color']

In [8]:
# scale the data: 
to_scale = list(clean_df.columns)
train, validate, test = wr.scale_data(train, validate, test, to_scale)

Cluster 1: Train

In [11]:
X1 = train[['alcohol', 'sulphates']]
X1.head()

#make the thing: 
kmeans = KMeans(n_clusters=4)

#fit the thing (ONLY ON TRAIN)
kmeans.fit(X1)

#Use the thing:
kmeans.predict(X1)

array([1, 0, 2, ..., 1, 0, 0], dtype=int32)

In [12]:
# make a new column names cluster in iris and X dataframe

train['cluster_1'] = kmeans.predict(X1)

X1['cluster_1'] = kmeans.predict(X1)

df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality wine_color  
0      9.4        5        red  
1      9.8        5        red  
2      9.8        5        red  
3      9.8        6        red  
4      9.4        5        red

Cluster 1: Validate


In [14]:
validate.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
5258       0.207792          0.548780       0.2000        0.082515   0.217742   
1531       0.298701          0.762195       0.1250        0.086444   0.580645   
849        0.337662          0.670732       0.2625        0.039293   0.572581   
5709       0.493506          0.390244       0.3375        0.023576   0.354839   
5206       0.389610          0.073171       0.2250        0.031434   0.306452   

      free_sulfur_dioxide  total_sulfur_dioxide   density        pH  \
5258             0.297297              0.359050  0.085188  0.396552   
1531             0.108108              0.062315  0.577877  0.741379   
849              0.099099              0.074184  0.614749  0.724138   
5709             0.198198              0.551929  0.280992  0.413793   
5206             0.261261              0.246291  0.280992  0.456897   

      sulphates   alcohol   quality  is_white  
5258   0.365854  0.838710  0.833333       0.0  
1531   0.524390  0.354839  0.333333       1.0  
849    0.524390  0.290323  0.333333       1.0  
5709   0.182927  0.580645  0.333333       0.0  
5206   0.378049  0.516129  0.500000       0.0

In [15]:
V1 = validate[['alcohol', 'sulphates']]

#use the thing:  
kmeans.predict(V1)

array([0, 1, 1, ..., 0, 1, 2], dtype=int32)

In [17]:
T1 = train[['alcohol','sulphates']]

#use the thing:
kmeans.predict(T1)

array([1, 0, 2, ..., 1, 0, 0], dtype=int32)